sudo: required

services:
  - docker

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
matrix:
  allow_failures:
    - php: '5.6'
script: phpunit tests/QuickFormPHP7Test.php

after_success:
  - sh .travis/deploy_dockerhub.sh