sudo: required

services:
  - docker

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
matrix:
  allow_failures:
    - php: '5.6'
    - php: '7.0'
script: phpunit --bootstrap bootstrap.php tests

after_success:
  - sh .travis/deploy_dockerhub.sh